### ISSUE TITLE
gitbook-cli项目怎么样了

### ISSUE THREAD

**Issue by chuck6** [bxiaopeng/thegreatmarkdown#1]
毕老师，你好。了解到在github中gitbook-cli项目已经很长时间没有更新了，上面提及上已经遭到了启用，
![image](https://user-images.githubusercontent.com/18416406/66972959-f3727200-f0c8-11e9-9145-1317098c457b.png)，请问下，有没有替代的项目啊，实现gitbook类型的功能啊？
谢谢你了！

**Comment by mansucache** [comment]
有个项目 [mdBook](https://github.com/rust-lang-nursery/mdBook) 跟 Gitbook 很像，是用 Rust 开发的，我在持续关注中，你也可以了解一下。

**Comment by chuck6** [comment]
毕老师，你好。
    不好意思，刚出差回来，回复你的邮件。谢谢的建议，我再学习学习！



chuck.xu@139.com
 
发件人： bxp
发送时间： 2019-10-18 18:15
收件人： bxiaopeng/thegreatmarkdown
抄送： chuck6; Author
主题： Re: [bxiaopeng/thegreatmarkdown] gitbook-cli项目怎么样了 (#1)
有个项目 mdBook 跟 Gitbook 很像，是用 Rust 开发的，我在持续关注中，你也可以了解一下。
