### ISSUE TITLE
书中 2.2.7 的锚点问题

### ISSUE THREAD

**Issue by WarsFeng** [bxiaopeng/thegreatmarkdown#2]
有幸买了这本书, 2.2.7 锚点中: 

> 在锚点名中不能含有空格, 也不能含有特殊字符

建议把空格的代替符号 `-` 加上, 比较喜欢在标题里写空格 -。-, 如: 

```markdown
## 1 排版

### 1.1 推荐排版结构
```

锚点就可以写成这样子呢: `[1 排版](#1-排版)`

**Comment by mansucache** [comment]
多谢建议，已添加，在[这里](https://github.com/bxiaopeng/thegreatmarkdown/blob/master/docs/01/gfm/gfm.md#%E9%94%9A%E7%82%B9)
